title: Data Science and Bioscience Consulting
logo: /assets/img/datinsights_logo.png
description: We help you manage, maximize, and interpret your data to make smart strategic decisions.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
email: contact@datinsights.com
linkedin: https://www.linkedin.com/in/yann-dufour/
